name: dengai
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.15
  - pip
  - pytorch=2.4.1
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - pandas=2.2.3
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - xgboost=2.1.1
  - mlflow=2.16.2
  - hyperopt=0.2.7
  - pip:
      - jupyter==1.1.1
      - sensai==1.2.1
